### ISSUE TITLE
I cannot run the program

### ISSUE THREAD

**Issue by AndreaLagomarsino** [lukasjarzembowski/Arduino-TTL-Trigger#1]

**Comment by lukasjarzembowski** [comment]
Dear @AndreaLagomarsino - first of all, thank you for finding this repro, I've never thought this little build would be useful to anyone! Since you edited your post I assume you could resolve the issue? Would you be open to sharing how you fixed it for any future users? Since I made a this a while back I haven't really made sure that it works with current versions of Python and the PySimpleGUI library.
